name: Main Branch CI
on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Unit-Tests
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Select Xcode 14.2
        run: sudo xcode-select -s /Applications/Xcode_14.2.app
      - name: Setup Swift version
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.7.2"
      - name: Run unit tests
        run: |
          swift test --enable-code-coverage
  update_documentation:
    name: Update documentation
    runs-on: macos-latest
    needs: tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Select Xcode 14.2
        run: sudo xcode-select -s /Applications/Xcode_14.2.app
      - name: Setup Swift version
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.7.2"
      - name: Generate documentation
        uses: fwcd/swift-docc-action@v1
        with:
          target: SemanticVersioningKit
          output: ./docs
          hosting-base-path: SemanticVersioningKit
          disable-indexing: "true"
          transform-for-static-hosting: "true"
      - name: Commit documentation
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./docs/**
          git commit -m "chore(documentation): Generate documentation"
          git push
